name: Continuous Delivery

on:
  push:
    branches:
      - main
  release:
    types:
      - released
      - published

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/continuous-integration.yml
  deploy:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
      - name: pre-processing
        run: |
          yarn install --frozen-lockfile
          yarn build
          mv appsscript.json dist/appsscript.json
      - name: Set Clasprc Config
        uses: iwaseshi/clasp-deploy-action@main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ID_TOKEN: ${{ secrets.ID_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
      - name: deploy-gas
        env:
          CLASP_SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
        run: |
          yarn run make-clasp-json
          echo "y" | yes | head -n 1 | yarn run push
